# Generated by Django 6.0.5 on 2026-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('orgasm', 'Orgasmus'), ('injury', 'Verletzung'), ('cleaning', 'Reinigung'), ('basiccleaning', 'Grundreinigung'), ('adjustment', 'Einstellung')], default='cleaning', max_length=20)),
            ],
        ),
    ]
