# Generated by Django 6.0.5 on 2026-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('cleaning', 'Reinigung')], default='cleaning', max_length=20)),
            ],
        ),
    ]
