# Generated by Django 6.0.5 on 2026-05-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltTracker', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='belt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='BeltTracker.chastitybelttype'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
